#%RAML 1.0 DataType

type: object
properties:
  prodavacID?: integer
  ime: string
  prezime: string
  JMBG: integer
  adresa: string
  kontakt: string
  datumZaposlenja: date-only
  korisnikID: integer