#%RAML 1.0 NamedExample
value:
  -
    dodatniZahtevID: 1
    opisZahteva: Paket opreme za gume
    datumPodnosenja: 2017-06-23
    kupoprodajniUgovorID: 1
  -
    dodatniZahtevID: 2
    opisZahteva: Zatamnjenje stakala
    datumPodnosenja: 2018-05-17
    kupoprodajniUgovorID: 2
   