#%RAML 1.0 NamedExample
value:
  -
   poliseOsiguranjaID: 1
   vaziOd: 2017-04-23
   vaziDo: 2020-07-23
   osiguravajucaKucaID: 1

  -
    poliseOsiguranjaID: 2
    vaziOd: 2015-09-12
    vaziDo: 2024-05-16
    osiguravajucaKucaID: 6


