#%RAML 1.0 NamedExample
value:
  -
   prodavacID: 1
   ime: Miomir 
   prezime: Mirić
   JMBG: 1123450439343
   adresa: Majska 44
   kontakt: 067-44-44-123
   datumZaposlenja: 2001-02-02
   korisnikID: 1
  -
    prodavacID: 2
    ime: Milica
    prezime: Jovanović
    JMBG: 3423454345674
    adresa: Vojvode Stepe 134
    kontakt: 066-33-33-234
    datumZaposlenja: 2006-08-08
    korisnikID: 2

