#%RAML 1.0 NamedExample
value:
  -
    servisID: 1
    datumServisiranja: 2019-03-12
    opis: Postavljanje i zamena sezonskih guma
    cenaServisa: 5000
    aktuelan: false
  -
    servisID: 2
    datumServisiranja: 2020-01-23
    opis: Testiranje rada kontrolne table
    cenaServisa: 6500
    aktuelan: false
